"""empty message

Revision ID: 2a8b9eeb2bdf
Revises: 017e00022302
Create Date: 2024-08-14 15:26:50.957150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8b9eeb2bdf'
down_revision = '017e00022302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('skin_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
