"""empty message

Revision ID: f88acb87e0dd
Revises: 2a8b9eeb2bdf
Create Date: 2024-09-16 17:04:52.216540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88acb87e0dd'
down_revision = '2a8b9eeb2bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('hair_color')
        batch_op.drop_column('gender')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('terrain')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
